# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['clickcoiff@yopmail.com']
 
    transport: gmail
    username:  halit.cinici@gmail.com
    password:  010792hc
